#!/bin/bash
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
POWDER_BLUE=$(tput setaf 153)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
BRIGHT=$(tput bold)
NORMAL=$(tput sgr0)
BLINK=$(tput blink)
REVERSE=$(tput smso)
UNDERLINE=$(tput smul)

UX_VERSION=$(docker exec -it threatrix-threat-center cat /var/www/html/assets/version.json | grep version | awk '{ print $2}' | sed 's/"//g')
if [ $? -ne 0 ]; then
        UX_VERSION="unknown"
fi

APP_VERSION=$(docker exec -it threatrix-hybrid-app cat /opt/threatrix/version)
if [ $? -ne 0 ]; then
        APP_VERSION="unknown"
fi

echo $GREEN "The following versions of Threatrix components were found in your Hybrid Envirnment:"
echo
echo "$BLUE  Threat Center: $YELLOW $UX_VERSION"
echo "$BLUE  APP          : $YELLOW $APP_VERSION"
echo
echo $NORMAL
