#!/bin/bash

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
POWDER_BLUE=$(tput setaf 153)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
BRIGHT=$(tput bold)
NORMAL=$(tput sgr0)
BLINK=$(tput blink)
REVERSE=$(tput smso)
UNDERLINE=$(tput smul)

OLD_UX_VERSION=""
OLD_APP_VERSION=""
UX_VERSION=""
APP_VERSION=""

OLD_UX_VERSION=`docker exec -it threatrix-threat-center cat /var/www/html/assets/version.json | grep version | awk '{ print $2}'| sed 's/"//g' | tr -cd '[:print:]'`

CHECK=$(docker exec -it threatrix-threat-center cat /var/www/html/assets/version.json)
if [ $? -ne 0 ]; then
	OLD_UX_VERSION=unknown
fi

OLD_APP_VERSION=`docker exec -it threatrix-hybrid-app cat /opt/threatrix/version | tr -cd '[:print:]'`
CHECK=$(docker exec -it threatrix-hybrid-app cat /opt/threatrix/version)
if [ $? -ne 0 ]; then
	OLD_APP_VERSION=unknown
fi



banner()
{
  echo $BLUE $UNDERLINE "                                            " $NORMAL
  echo
  echo $BRIGHT $BLUE "   $@" $NORMAL
  echo "                                            "
  echo $BRIGHT $BLUE "   `date`" $NORMAL
  echo $BLUE $UNDERLINE "                                            " $NORMAL
  echo
}

banner "Welcome to Threatrix Hybrid Update Utility"
UX=latest
APP=latest
ARG0=$(basename "$0")

usage()
{
  echo "Usage: $BRIGHT $ARG0 -h -u <ux tag> -a <app tag>"
  echo " -h : Help"
  echo " -u <ux tag>: Version of the UX image you want to upgrade to. Default is latest"
  echo " -a <app tag>: Version of the APP image you want to upgrade to. Default is latest"
  echo
  exit 1
}

while getopts ":u:a:d:h" opt; do
  case ${opt} in
    h ) # process option h
        usage
        exit 1
        ;;
    u ) # UX Version
        UX=$OPTARG
        ;;
    a ) # App version
        APP=$OPTARG
        ;;
    default )
        usage
        exit 1
        ;;
    :)
        echo "Error: Option -$OPTARG requires an argument."
        usage
        exit 1
  esac
done

echo  $GREEN "Updating your Hybrid Envirnment with the following components:"
echo
echo "$BLUE Threat Center: $YELLOW $UX"
echo "$BLUE APP          : $YELLOW $APP"
echo $NORMAL

while true; do
    read -p " Do you want to continue? ($GREEN y $WHITE or $RED n $WHITE) " yn
    case $yn in
        [Yy]* ) echo; echo $GREEN "Proceeding with install..."; echo $NORMAL; break;;
        [Nn]* ) echo; echo $RED "Aborting install!"; echo $NORMAL; exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

echo $GREEN "Updating Threatrix App and Threat Center...."
sudo docker container rm -f threatrix-threat-center threatrix-hybrid-app > update.log
sudo docker pull threatrix/hybrid-app:$APP >> update.log
sudo docker pull threatrix/threat-center:$UX >> update.log

echo $GREEN "Restarting Threatrix App and Threat Center containers...."
sudo docker run -d --restart always --network=host --name threatrix-hybrid-app -e LOCAL_IP=`hostname -I | awk  '{print $1}'` --hostname hybrid -d threatrix/hybrid-app:$APP >> update.log

if [ $? -ne 0 ]; then 
	echo $RED "Failed to start Threatrix Application. Please correct the problem and update...."
	echo $NORMAL
	exit
fi

sudo docker run -d --restart always --network=host --name threatrix-threat-center threatrix/threat-center:$UX >> update.log

if [ $? -ne 0 ]; then 
	echo $RED "Failed to start Threatrix Threat Center. Please correct the problem and update...."
	echo $NORMAL
	exit
fi

#wait for containers to come up
sleep 30

echo
UX_VERSION=$(docker exec -it threatrix-threat-center cat /var/www/html/assets/version.json | grep version | awk '{ print $2}'| sed 's/"//g' |tr -cd '[:print:]')
CHECK=$(docker exec -it threatrix-threat-center cat /var/www/html/assets/version.json)
if [ $? -ne 0 ]; then
	UX_VERSION="unknown"
fi

APP_VERSION=`docker exec -it threatrix-hybrid-app cat /opt/threatrix/version | tr -cd '[:print:]'`
CHECK=$(docker exec -it threatrix-hybrid-app cat /opt/threatrix/version)
if [ $? -ne 0 ]; then
	APP_VERSION="unknown"
fi

echo $GREEN "Upgraded the following Threatrix components in your Hybrid envirnment:"
echo $NORMAL
echo "$BLUE Threat Center: $WHITE from $YELLOW $OLD_UX_VERSION $WHITE to $GREEN $UX_VERSION"
echo "$BLUE APP          : $WHITE from $YELLOW $OLD_APP_VERSION $WHITE to $GREEN $APP_VERSION"
echo $NORMAL
banner "Threatrix Hybrid update complete!"
